### ISSUE TITLE
Docker CI

### ISSUE THREAD

**Issue by oke-aditya** [oke-aditya/template_python#10]
## 🚀 Feature

We have a minimalistic dockerfile which works!

To make stuff easier to deploy we need a CI for Docker. 
Docker sample CIs are available on GitHub actions.
It would be great to add that and will help in deploying to Docker.

Sample CI Workflows is [here](https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml) ! 

Can be customized for this.

**Comment by oke-aditya** [comment]
Additionally if people can publish docker image to a registry, much better !
Here is CI for [it](https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml).

**Comment by oke-aditya** [comment]
@ayush5588 You might be interested in this

**Comment by oke-aditya** [comment]
Seems like nobody want CI issues ☹️ . Let me handle this in a fresh PR.

**Comment by Gau02** [comment]
@oke-aditya, Do you just want to build already present Dockerfile and put a generated image into registry?

**Comment by oke-aditya** [comment]
I have a Dockerfile in this repository which should probably build. This should be checked on every PR using CI actions. And should get deployed using GitHub actions.

As simple as shipping a Python package using Docker. And then deploying to registry on Release.

**Comment by Gau02** [comment]
> I have a Dockerfile in this repository which should probably build. This should be checked on every PR using a CI actions. And should get deployed using GitHub actions.

let me give it a try 🙂

**Comment by oke-aditya** [comment]
Have a try, The CI action is one which I mentioned. You might need minor edit in `DockerFile`
