### ISSUE TITLE
Github actions needed for using this template

### ISSUE THREAD

**Issue by ramaneswaran** [oke-aditya/template_python#3]
What are the Github actions i need to enable to make the CI and docs to work

**Comment by oke-aditya** [comment]
There are 4 actions in the .github folder.

1. CI test (ci-testing.yml):- This does not need any configuration from users. This build the tests from tests folder using pytest.
It is initalized automatically no changes required. It build only on PRs to master and to master branch. You can edit it and extend it.

2. black formatter (black.yml): - This checks for black code formatting both on PRs to master and for master. This too does not need any extra configurations.

3. Building docs (docs-build.yml): - This only builds the docs whenever PR is raised to master branch.
This needs edit from user side. You need to replace your repo name in `pip install git+git://github.com/oke-aditya/template_python.git` in this line.

4. Pushing Docs (docs-deploy.yml): - This builds the docs and pushes to gh-pages whenever PR is **merged** to master branch.
This needs edit from user side. You need to replace your repo name in `pip install git+git://github.com/oke-aditya/template_python.git` in this line.

**Comment by ramaneswaran** [comment]
Thank you
