### ISSUE TITLE
Bump code coverage to 100

### ISSUE THREAD

**Issue by oke-aditya** [oke-aditya/template_python#7]
## 🐛 Bug

Seems to be simple.
This is a template repository so it should probably have 100 % code coverage.

We need to write tests that will simple trigger the files to have them tested.

**Comment by andrefpoliveira** [comment]
Hey I would like to work on this as part of my Hacktoberfest. But I'm a little confused. The tests that I would create are random? Because you don't really have any code to be tested right? Sorry if I'm mistaken

**Comment by oke-aditya** [comment]
Yes, I'm also a bit unsure about this issue. I had written a simple test [here](https://github.com/oke-aditya/template_python/blob/master/tests/test_hello.py), 

I thought after this test the code coverage would be 100 %. 

But it wasn't.

I guess something as simple as [this](https://github.com/pytorch/vision/blob/master/test/smoke_test.py) smoke test would bump up the code coverage. 

Anyways I will accept PR for smoke test.

This code is entirely packaged. Like a python package.

So people should be able to use

```
from template_python import *
from template_python.src import *
```

This repository is a template, hence shouldn't have code in it :-) 

I will share a preview of codecoverage so that you know where we are missing tests.

**Comment by oke-aditya** [comment]
have a look [here](https://github.com/oke-aditya/template_python/pull/6)

If by any chance, we can't bump code coverage to 100 % (Coz maybe since there is no code what will code coverage even do?)

It is safe to close this issue then. 👍  Have a go

**Comment by andrefpoliveira** [comment]
Thanks! I will check it out!

**Comment by andrefpoliveira** [comment]
@oke-aditya as the only functions that will be tested are the ones we submit (meaning they don't have any base related) I would consider that coverage tests for this repo are not necessary :)

**Comment by oke-aditya** [comment]
Yes. We don't have functions to test against. Again reason being this is a template. 

Hence I left the `test_hello.py` file. Which demonstrates how test could be done. 

So just a smoke test should be good. (Which apparently I leaked. :( Not giving a chance for people to think)

@andrefpoliveira I guess you can solve this issue easily now. Can you have a look at other as well? 

I have hinted a lot of stuff how to solve them. They too require minimal task. Luckily, I know the solutions for other issues 👍

**Comment by oke-aditya** [comment]
Hope you know the contributing process. Same as for any GitHub repository. ICYMI [here](https://github.com/oke-aditya/template_python/blob/master/CONTRIBUTING.md) it is.
